### ISSUE TITLE
Change order

### ISSUE THREAD

**Issue by finderos47** [s373r/privatediary-downloader#1]
Hello, when I download using src/main.js output file print notes from from newest to oldest records, newest records is on the start of file, but how to change order in script so that in output file.txt will be from oldest to newest at end?

**Comment by s373r** [comment]
Hello @finderos47 👋 

Sorry for the long answer :(
Notes ordering isn't supported at this time, but I'll implement this feature since you need it

I'll tag you when it's ready

**Comment by s373r** [comment]
Hello @finderos47! I have an update for you:

**Comment by s373r** [comment]
Hello @finderos47, I have an update for you:

Sorting support feature has been added in https://github.com/s373r/privatediary-downloader/pull/2 (1.1.0 version)

Please update/reinstall repo and use the following command line:
```
$ node . -u USER -p PASSWORD --sort asc
```

Let me know if you have any difficulties

**Comment by s373r** [comment]
I close the issue since no feedback but the requested feature has been implemented

**Comment by finderos47** [comment]
Hello s373r since you make update of script I can't run it with command starting with node . (node . -u USER -p PASSWORD --sort asc)   what should i install in ubuntu 20.04 or what else command I must enter ins terminal.

**Comment by s373r** [comment]
@finderos47 , could you please attach the error output?

>  what should i install in ubuntu 20.04 or what else command I must enter ins terminal.

It depends -- firstly, we need to analyze the output and after that, we'll get the next steps

**Comment by finderos47** [comment]
Hello s373r, sorry for late reply, so on my side your script not working or I do something wrong,
Here is terminal outpu, I change username and password:
┌─[✗]─[user@parrot]─[~/privatediary-downloader]
└──╼ $sudo node . -u user -p pass -b firefox -s asc
file:///home/user/privatediary-downloader/src/cli.js:41
const testcafe = await createTestCafe();
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
┌─[✗]─[user@parrot]─[~/privatediary-downloader]
└──╼ $sudo node . -u user -p pass
file:///home/user/privatediary-downloader/src/cli.js:41
const testcafe = await createTestCafe();
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
┌─[✗]─[user@parrot]─[~/privatediary-downloader]
└──╼ $node . -u user -p pass
file:///home/user/privatediary-downloader/src/cli.js:41
const testcafe = await createTestCafe();
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
┌─[✗]─[user@parrot]─[~/privatediary-downloader]
└──╼ $sudo node -u user -p pass
node: bad option: -u
┌─[✗]─[user@parrot]─[~/privatediary-downloader]
└──╼ $sudo node . -u user -p pass
file:///home/user/privatediary-downloader/src/cli.js:41
const testcafe = await createTestCafe();
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

Kind Regards, finderos47

**Comment by s373r** [comment]
hello @finderos47 

Next steps
------------
1) You don't need to use `sudo` with the command, just use
```
node . -u USER -p PASS
```
2) Looks like you have the old `node` version. Please provide the output of each commands:
```shell
node --version       # prints node version
node . --version     # prints app version
git log --oneline -1 # prints the latest git commit 
```


--- 

**PS.** A friendly request: please paste the output into code blocks, like this:
```
┌─[✗]─[user@parrot]─[~/privatediary-downloader]
└──╼ $sudo node . -u user -p pass -b firefox -s asc
file:///home/user/privatediary-downloader/src/cli.js:41
const testcafe = await createTestCafe();
^^^^^

SyntaxError: Unexpected reserved word
...
```

For that, just wrap the output into ` ``` ``` `, for example:
````
``` 
output
```
````

More details [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
